set encoding=utf-8
filetype on " not on by default in Mac, so stop it barfing when we try to...
filetype off " ...turn it off!

" Bundle setup
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()
" Original repos on github
Bundle 'gmarik/vundle'
Bundle 'davidhalter/jedi-vim'
Bundle 'tpope/vim-sensible'
Bundle 'kien/ctrlp.vim'
Bundle 'scrooloose/nerdtree'
"Bundle 'hallettj/jslint.vim'
filetype plugin indent on " required for Bundle to work

" Use spaces instead of tabs
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

syntax enable
set number
set t_Co=256  " make use of 256 terminal colors
color summerfruit256
let mapleader=","
let g:ctrlp_user_command = "find %s -type f | egrep -v '/\.(git|hg|svn|pythonbrew)|solr|tmp/' | egrep -v '\.(png|exe|jpg|gif|jar|class|swp|swo|log|gitkep|keepme|so|o|pyc|zip|swp|un~)$'"

" ,r will reload the ~/.vimrc file
map <leader>r :so $MYVIMRC<CR>

" show whitespace
set listchars=tab:→.,trail:.,extends:#,nbsp:.,precedes:<
set list
highlight SpecialKey term=standout ctermfg=grey ctermbg=yellow guifg=grey guibg=yellow

" NERDTree shortcut
map <leader>nt :NERDTreeToggle<CR>

